<?php

namespace Taskio\Repository;

/**
 * CustomerNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerNoteRepository extends AbstractRepository
{
}
