<?php

namespace Taskio\Repository;

/**
 * TaskCycleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskCycleRepository extends AbstractRepository
{
}
