<?php

namespace Taskio\Repository;

/**
 * TaskStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskStatusRepository extends AbstractRepository
{
}
