<?php

namespace Taskio\Repository;

/**
 * UserTimeRowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTimeRowRepository extends AbstractRepository
{
}
