version: '2'
services:
  web:
    container_name: web
    image: nginx:latest
    volumes:
        - ./:/var/www/symfony/
        - ./conf/server.conf:/etc/nginx/conf.d/site.conf
    ports:
        - 80:80
    links:
        - mysql
        - memcached
        - php
    restart: always
    networks:
      - vpcbr
    depends_on:
      - php
  php:
    container_name: php
    build: docker/php-fpm
    volumes:
        - ./:/var/www/symfony/
    networks:
      - vpcbr
    restart: always
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    networks:
      - vpcbr
  memcached:
    container_name: memcached
    image: memcached:latest
    restart: always
    networks:
      - vpcbr
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
