<?php

namespace AppBundle\Repository;

/**
 * CustomerItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerItemRepository extends AbstractRepository
{
}
