<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * TimeRowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeRowRepository extends EntityRepository
{
    /**
     * @param User $user
     * @param string $date
     * @return null|object
     */
    public function getDateInformation($user, $date)
    {
        return $this->findOneBy(
            array(
                'user' => $user,
                'date' => new \DateTime($date)
            )
        );
    }
}
