<?php

namespace AppBundle\Repository;

/**
 * TimeVacationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeVacationRepository extends AbstractRepository
{
}
