<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Scheb\TwoFactorBundle\Model\PersisterInterface;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserLoaderInterface, PersisterInterface
{
    public function loadUserByUsername($username)
    {
        return $this->createQueryBuilder('u')
            ->where('u.username = :username OR u.email = :email')
            ->setParameter('username', $username)
            ->setParameter('email', $username)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * Persist the user entity.
     *
     * @param object $user
     */
    public function persist($user)
    {
        $em = $this->getEntityManager();
        $em->persist($user);
        $em->flush();
    }
}
