parameters:

services:
    login_listener:
        class: AppBundle\EventListener\LoginListener
        arguments: ['@security.context', '@doctrine']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
    kernel.event_listener.json_request_transformer:
        class: Qandidate\Common\Symfony\HttpKernel\EventListener\JsonRequestTransformerListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }
    memcached:
        class: Memcached
        calls:
            - [ addServer, [%memcache_server%, %memcache_port%] ]

    session.handler.memcached:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments: [ @memcached, { prefix: 'mem_task_', expiretime: 604800 } ]