parameters:

services:
    login_listener:
        class: Taskio\EventListener\LoginListener
        arguments: ['@security.context', '@doctrine']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
    kernel.event_listener.json_request_transformer:
        class: Qandidate\Common\Symfony\HttpKernel\EventListener\JsonRequestTransformerListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }
    memcached:
        class: Taskio\Utils\MemcachedWrapper
        arguments:
            persistent_id: 'sess_'
        calls:
            - [ setOption, [18, true] ]
            - [ addServer, ['%memcache_server%', '%memcache_port%'] ]
    elasticsearch:
        class: Taskio\Service\Elasticsearch
        arguments: [ '%elastic_host%', '%elastic_port%', '%elastic_scheme%', '%elastic_user%', '%elastic_pass%' ]
    app_consumer:
        class: Taskio\Consumer\AppConsumer
        arguments: [ '@doctrine' ]
    media:
        class: Taskio\Service\Cloudinary
        arguments: [ '@doctrine.orm.entity_manager', [ cloud_name: '%cloudinary_host%', api_key: '%cloudinary_user%', api_secret: '%cloudinary_pass%' ] ]
    cache:
        class: Taskio\Service\Cache
        arguments: [ '@memcached' ]
    session.handler.memcached:
            class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
            arguments: ['@memcached', { prefix: 'sess_', expiretime: '86400' }]